version: "3.7"

services:

    zookeeper:
      image: "bitnami/zookeeper:latest"
      container_name: zookeeper
      networks:
        - cryptoViz
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes


    kafka1:
      image: "bitnami/kafka:latest"
      container_name: kafka1
      networks:
        - cryptoViz
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
        - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092"
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CREATE_TOPICS="kafka-nifi-src:1:3,kafka-nifi-dst:1:3,kafka-final:1:3"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 1G
      restart: always

    kafka2:
      image: "bitnami/kafka:latest"
      container_name: kafka2
      networks:
        - cryptoViz
      ports:
        - "9093:9092"
      environment:
        - KAFKA_BROKER_ID=2
        - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092"
        - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 1G
      restart: always

    kafka3:
      image: "bitnami/kafka:latest"
      container_name: kafka3
      networks:
        - cryptoViz
      ports:
        - "9094:9092"
      environment:
        - KAFKA_BROKER_ID=3
        - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092"
        - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 1G
      restart: always


    spark-master:
      image: bitnami/spark:latest
      ports:
        - "7077:7077"
      networks:
        - cryptoViz
      environment:
        - SPARK_MODE=master

    spark-worker:
      image: bitnami/spark:latest
      networks:
        - cryptoViz
      ports:
        - "8081:8081"
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      restart: always


    kafka-producer:
      build:
        context: ./kafka/producer
        dockerfile: Dockerfile
      container_name: kafka-producer
      environment:
        BINANCE_WEBSOCKETS: "wss://stream.binance.com:9443/ws/btcusdt@kline_1m"
        TOPIC: kafka-nifi-src
        BOOTSTRAP_SERVER: "kafka1:9092,kafka2:9092,kafka3:9092"
      networks:
        - cryptoViz
      depends_on:
        - kafka1
        - kafka2
        - kafka3
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 2G
          reservations:
            cpus: '0.25'
            memory: 1G
      restart: always

    kafka-consumer:
      build:
        context: ./kafka/consumer
        dockerfile: Dockerfile
      container_name: kafka-consumer
      environment:
        TOPIC: kafka-nifi-dst
        BOOTSTRAP_SERVER: "kafka1:9092,kafka2:9092,kafka3:9092"
        PRODUCER_TOPIC: kafka-final
      networks:
        - cryptoViz
      volumes:
        - ./kafka/consumer/app:/app
      depends_on:
        - kafka1
        - kafka2
        - kafka3
        - kafka-producer
        - spark-master
        - spark-worker
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 8G
          reservations:
            cpus: '0.25'
            memory: 5G
      restart: always


networks:
  cryptoViz: